version: 2
jobs:
  build:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run: |
          # Installing Deps
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          mv .env.deploy .env
          # Populating .env
          sed -i s#%AWS_ACCESS_KEY%#$AWS_ACCESS_KEY#g .env
          sed -i s#%AWS_SECRET_KEY%#$AWS_SECRET_KEY#g .env
          sed -i s#%CIRCLE_CI_TOKEN%#$CIRCLE_CI_TOKEN#g .env
          sed -i s#%PROJECT_NAME%#$PROJECT_NAME#g .env
          sed -i s#%NLB_LISTENER_PORT%#$NLB_LISTENER_PORT#g .env
          # Building docker image
          cd deploy
          ./build-images.sh $PROJECT_NAME

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: inapps-test
          filters:
            branches:
              only:
                - feat/deploy
